  json.id classroom.id
  json.teacher_id classroom.teacher_id
  json.student_id classroom.student_id
  json.course_id classroom.course_id
  json.teacher_first_name classroom.teacher.first_name
  json.teacher_last_name classroom.teacher.last_name
  json.teacher_email classroom.teacher.email
  json.student_first_name classroom.student.first_name
  json.student_last_name classroom.student.last_name
  json.student_email classroom.student.email
  json.course classroom.course.name